spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?autoReconnect=true&useSSL=false
    druid:
          initialSize: 30
          keepAlive: true
          minIdle: 10
          maxActive: 100
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: true
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 40
          filters: stat,wall
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          stat-view-servlet:
            allow: 127.0.0.1
  session:
    store-type: redis
    redis:
      namespace: seckill

  http:
    multipart:
      max-file-size: 300Mb #单个文件的大小
      max-request-size: 600Mb
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1800

    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000

  mail:
    host: smtp.exmail.qq.com
    username: admin@wenfan.club
    password: Wenfan0934
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
server:
  port: 8060
  session:
    timeout: 120
  connection-timeout: 180000
  context-path: /api/
  tomcat:
    max-connections: 20000
    max-threads: 800
    accept-count: 1000
    min-spare-threads: 50




token:
  expire:
    seconds: 720000
    jwtSecret: wenfan666@

com:
  wenfan:
    security:
      browser:
        unAuthorizationUrl: /server/api/item/**

mybatis:
  mapperLocations: classpath*:com/wenfan/seckill/mapper/xml/*.xml
  type-aliases-package: com.wenfan.seckill.entity
logging:
  level:
    com.wenfan.seckill.mapper : debug
  file: seckill.log
  path: var\local\youtube\log 

# windows 启动 rocketmq    1.start mqnamesrv.cmd     2.  start mqmybroker.cmd -n localhost:9876
rocketmq:
  nameserver:
    addr: 127.0.0.1:9876
  topicname: stock



